### ISSUE TITLE
抽奖详情

### ISSUE THREAD

**Issue by WillieWangWei** [WillieWangWei/Lotteryyy#1]
![](https://upload-images.jianshu.io/upload_images/4518631-c5b8bcb44fe70634.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

感谢大家对 **[SwiftUI Tutorials 翻译项目](https://github.com/WillieWangWei/SwiftUI-Tutorials)** 的支持，也很开心有几百人聚在一起学习 SwiftUI ，共同解决实际问题。年底了，我决定搞个抽奖一起高兴一下，给大家在节日期间的学习提供更多的选择。

> 关注我，下次抽奖早知道😊

# 奖品

* **[泊学](https://boxueio.com/) 一个月会员订阅，价值59元。**
* **[JetBrains 全家桶](https://www.jetbrains.com/store/#commercial?billing=monthly) 正版授权3个月序列号，价值约452.90元。**

中奖者将获得一组上面的奖品，共抽取10位参与者，奖品总价值约 (59 + 452.90) * 10 = **5119 元**。

**什么是泊学？**

> 想循序渐进的跟上最新的技术趋势？想不为了学点东西到处搜索？想找个伙伴一起啃原版技术经典书？技术之外，还想了解高效的工作流技巧？甚至，工作之余，想找点儿东西放松心情？没问题，我们用4K开发视频，配以详尽的技术文档，以及精心准备的广播节目，让你渴望成长的技术需求，也是一种享受。

![部分泊学课程](https://upload-images.jianshu.io/upload_images/4518631-faa44a46dd6d2ca7.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![部分泊学课程](https://upload-images.jianshu.io/upload_images/4518631-1508eaf417fea7a5.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![部分泊学课程](https://upload-images.jianshu.io/upload_images/4518631-9552680557000634.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**什么是 JetBrains 全家桶？**

JetBrains 全家桶（[All Products Pack](https://www.jetbrains.com/all/)）内包含10款集成开发环境，2款插件以及3款分析软件，你可以随意使用。

![All Products Pack](https://upload-images.jianshu.io/upload_images/4518631-d64d5d49fce4e517.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

![All Products Pack](https://upload-images.jianshu.io/upload_images/4518631-5fd136ed288ee272.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

# 如何参与

在[这里](https://github.com/WillieWangWei/Lotteryyy/issues/1)发布评论，包括以下两张截图即可。

1. 点赞 [SwiftUI Tutorials 翻译项目](https://github.com/WillieWangWei/SwiftUI-Tutorials) 的截图，例：

![](https://upload-images.jianshu.io/upload_images/4518631-2ff416f356e63927.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

2. 加入 `SwiftUI 技术` 微信群之后的截图，例：

![](https://upload-images.jianshu.io/upload_images/4518631-70c262ff27e2a445.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

如果还没有加群，请扫码二维码，备注“SwiftUI”，我会拉你进群。

![](https://upload-images.jianshu.io/upload_images/4518631-99b225f2f19a1234.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

# 开奖

* 1月11日（周六）第一次开奖，抽出5名中奖者。
* 1月18日（周六）第二次开奖，抽出5名中奖者。

# 领奖

开奖后我会联系中奖者的微信，发送奖品🎁～

# 鸣谢

感谢 [泊学](https://boxueio.com/) 10 和 11 对本次抽奖活动的特别赞助。

***

按格式回复即可参与抽奖，祝你好运🍀

# Star 截图
你的图片...

# 群截图
你的图片...

**Comment by wxxsw** [comment]
<img width="942" alt="image" src="https://user-images.githubusercontent.com/921863/71575749-1f7a8c80-2b29-11ea-8cdf-82b201e53c24.png">
<img width="203" alt="image" src="https://user-images.githubusercontent.com/921863/71575760-25706d80-2b29-11ea-8e66-db88624a81c5.png">

**Comment by Heiyuan** [comment]
Star 截图
![](http://fattwo.oss-cn-beijing.aliyuncs.com/kzugq.png)
群截图
![](http://fattwo.oss-cn-beijing.aliyuncs.com/tvvea.png)

**Comment by zhai** [comment]
Star 截图

<img width="535" alt="WX20191230-172421@2x" src="https://user-images.githubusercontent.com/2810071/71575801-4042e200-2b29-11ea-8fc3-7fa8d98d052f.png">

群截图
![IMG_1218](https://user-images.githubusercontent.com/2810071/71575841-68324580-2b29-11ea-8714-1073ef90cb1d.PNG)

**Comment by zhaomengnan7526** [comment]
star截图
<img width="737" alt="截屏2019-12-30下午5 30 21" src="https://user-images.githubusercontent.com/17473395/71576099-61f09900-2b2a-11ea-8a51-1ddd39d1de5c.png">
群截图
<img width="1053" alt="截屏2019-12-30下午5 31 10" src="https://user-images.githubusercontent.com/17473395/71576112-6fa61e80-2b2a-11ea-8109-419013924dde.png">

**Comment by ChenMin0216** [comment]
![image](https://user-images.githubusercontent.com/11597613/71576308-2b674e00-2b2b-11ea-852e-8e4ec5cecb11.png)
![image](https://user-images.githubusercontent.com/11597613/71576332-45089580-2b2b-11ea-9e85-22685a39f5b6.png)
这辈子没中过奖，就看这一次了

**Comment by fuuqiu** [comment]
Star 截图
![WeChat109720671abe7e969622fbc09048569d](https://user-images.githubusercontent.com/35496061/71577578-adf20c80-2b2f-11ea-940f-3e56634e9224.png)


群截图
![WeChat08ee8fcbd1707e7943007e3f8cd1ef12](https://user-images.githubusercontent.com/35496061/71577583-b4808400-2b2f-11ea-9b30-94aefbcb18c2.png)
第一玩技术群活动 好奇

**Comment by StudentJeffRen** [comment]
Star 截图
![3F17F528-13B0-419B-91E1-C090B4AA3C09](https://user-images.githubusercontent.com/37734725/71592330-c2072f80-2b6a-11ea-8875-8af59b548a8a.png)
群截图
![0D9C6E25-A0FD-403F-9778-F083507C7430](https://user-images.githubusercontent.com/37734725/71592342-d2b7a580-2b6a-11ea-9f6a-72acff5e2cd4.png)

**Comment by zxiang2013** [comment]
**先赞一波，感谢无私奉献。**😙
![image](https://user-images.githubusercontent.com/5276499/71609113-e68df680-2bc0-11ea-9a83-b18677e36e8d.png)
![image](https://user-images.githubusercontent.com/5276499/71609123-f6a5d600-2bc0-11ea-9ac4-5c6deae4139a.png)

**Comment by HeySoyl** [comment]
# Star 截图

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/46934179/72161512-38255500-33fb-11ea-93bd-d006051eaa8e.png">

# 群截图

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/46934179/72161357-f3012300-33fa-11ea-94b3-e7288153fbbf.png">

**Comment by chrischen1021213933** [comment]
Star截图
<img width="1317" alt="star" src="https://user-images.githubusercontent.com/22274258/72197230-0099c580-345a-11ea-8c1a-2a081e6cb03b.png">
群截图
![qun](https://user-images.githubusercontent.com/22274258/72197237-0d1e1e00-345a-11ea-9d1e-2564bf1685cf.jpeg)

**Comment by WillieWangWei** [comment]
第一波抽奖幸运参与者产生，GitHub 昵称分别是

wxxsw
zhai
ChenMin0216
fuuqiu
zxiang2013

请以上参与者将邮箱私聊给我，我来发放奖品🎁

第二波开奖是1月19日，再错过就没机会啦。

**Comment by inkCrazy** [comment]
泊学/JetBrains 全家桶/SwiftUI Tutorials 翻译项目都挺香的
![截屏2020-01-1113 19 54](https://user-images.githubusercontent.com/12253453/72199343-bde5e680-3475-11ea-807f-a5b33163defb.png)
![截屏2020-01-1113 20 11](https://user-images.githubusercontent.com/12253453/72199344-bde5e680-3475-11ea-8237-36ac2d565620.png)

**Comment by WillieWangWei** [comment]
第二波抽奖幸运参与者产生，GitHub 昵称分别是

[Heiyuan](https://github.com/WillieWangWei/Lotteryyy/issues/1#issuecomment-569624379)
[zhaomengnan7526](https://github.com/WillieWangWei/Lotteryyy/issues/1#issuecomment-569626032)
[HeySoyl](https://github.com/WillieWangWei/Lotteryyy/issues/1#issuecomment-573064181)
[chrischen1021213933](https://github.com/WillieWangWei/Lotteryyy/issues/1#issuecomment-573269397)
[inkCrazy](https://github.com/WillieWangWei/Lotteryyy/issues/1#issuecomment-573283478)

请以上参与者将邮箱私聊给我，我来发放奖品🎁
